services:
  gitea:
    environment:
      # Database (database)[https://docs.gitea.com/administration/config-cheat-sheet/#database-database]
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${DB_HOST:-mysql:3306}
      GITEA__database__NAME: ${DB_NAME:?DB_NAME is required}
      GITEA__database__USER: ${DB_USER:?DB_USER is required}
      GITEA__database__PASSWD__FILE: /run/secrets/db_password
      GITEA__database__SSL_MODE: disable
      GITEA__database__LOG_SQL: false

    secrets:
      - db_password

secrets:
  db_password:
    file: ${SECRETS_DIR:?SECRETS_DIR is required}/env/${COMPOSE_PROJECT_NAME}/db_password
