services:
  gitea:
    environment:
      # Mailer (mailer)[https://docs.gitea.com/administration/config-cheat-sheet/#mailer-mailer]
      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__PROTOCOL: smtp
      GITEA__mailer__SMTP_ADDR: ${MAIL_SMTP_HOST:?MAIL_SMTP_HOST is required}
      GITEA__mailer__SMTP_PORT: ${MAIL_SMTP_PORT:?MAIL_SMTP_PORT is required}
      GITEA__mailer__FORCE_TRUST_SERVER_CERT: "false"
      GITEA__mailer__USER: ${MAIL_SMTP_USERNAME}
      GITEA__mailer__PASSWD__FILE: /run/secrets/mail_password
      GITEA__mailer__FROM: GITEA <${MAIL_FROM}>

    secrets:
      - mail_password

secrets:
  mail_password:
    file: ${SECRETS_DIR:?SECRETS_DIR is required}/env/000-generic/email/password
