services:
  npm:
    image: jc21/nginx-proxy-manager:${NPM_VER:?NPM_VER is required}
    hostname: npm.${STACK_DOMAIN:?STACK_DOMAIN is required}.local
    restart: ${RESTART:-unless-stopped}
    pull_policy: ${PULL_POLICY:-missing}

    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

    deploy:
      resources:
        limits:
          cpus: "${NPM_CPU_LIMIT:-1.0}"
          memory: ${NPM_MEM_LIMIT:-512M}

volumes:
  npm_data:
  npm_letsencrypt:
