include:
  - path:
      - ../services/base/passbolt/docker-compose.yml
      - ../services/base/passbolt/database/docker-compose.mariadb.yml
  - ../services/base/mariadb/docker-compose.yml

services:
  passbolt:
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    networks:
      - backend

  mariadb:
    networks:
      - backend

networks:
  backend:
    internal: true
