services:
  tor:
    image: ghcr.io/arasemco/tor:${TOR_VERSION:?TOR_VERSION is required}
    hostname: tor.${STACK_DOMAIN:?STACK_DOMAIN is required}.local
    restart: ${RESTART:-unless-stopped}
    pull_policy: ${PULL_POLICY:-missing}

    volumes:
      - tor_etc:/etc/tor
      - tor_var:/var/lib/tor

    deploy:
      resources:
        limits:
          cpus: "${TOR_CPU_LIMIT:-0.5}"
          memory: ${TOR_MEM_LIMIT:-256M}

volumes:
  tor_etc:
  tor_var:
