include:
  - docker-compose.backup.yml
  - docker-compose.homepage.yml

volumes:
  backup_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/raid/backup/archive/as01.omesa.net/containers/${COMPOSE_PROJECT_NAME}
      o: bind,nosuid,nodev
